name: 🔒 Add site with passkey support
description: Request that a site that supports passkey authentication be added.
title: Add [site name]
labels: add site
body:

  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to this project!
        Our site depends on user contributions to stay up to date. If you know how to write JSON files, we prefer you create a [pull request](https://github.com/2factorauth/passkeys/blob/master/CONTRIBUTING.md) instead of an issue.

        Please take time to fill out as much as possible in this form. We receive a lot of issues, and your thoroughness helps speed things up.
        If you cannot fill a field out, leave it blank and let us know why in the "Additional information" section.

  - type: input
    id: name
    attributes:
      label: Site name
      description: Official name of the site
      placeholder: YouTube
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Site URL
      description: Link to the main page
      placeholder: https://youtube.com
    validations:
      required: true

  - type: input
    id: doc
    attributes:
      label: Documentation URL
      description: |
        Link to documentation on how to enable passkey authentication on the site.
        Attach screenshots of the setup/login process if no public-facing documentation link is available, redacting any personal information.

  - type: input
    id: recovery
    attributes:
      label: Recovery Documentation URL
      description: |
        People sometimes lose their phones or security keys. If the site offers a way to recover an account in such an event, please link to a page describing how to recover an account.
        If the site doesn't provide such an option or has no public-facing documentation, leave this field blank.

  - type: checkboxes
    id: 2fa
    attributes:
      label: Supported options
      description: Check every passkey authentication method that the site supports.
      options:
        - label: Passwordless authentication
        - label: Passkey as MFA

  - type: textarea
    id: regions
    attributes:
      label: Regions served
      description: |
        Some sites have a limited market. If the site is only intended for users in certain countries or regions, please list those countries/regions below.
        For sites that technically are available globally but only of interest to a single region, please list the region.
        If the primary audience is residents in a larger region, like North America or Europe, you can list that region instead of each country.

  - type: checkboxes
    id: eligibility
    attributes:
      label: Eligibility
      description: |
        Check each box below to verify that the site meets our requirements for being listed.

        You can still create an issue even if a site does not meet these requirements.
        Leave any unmet requirements unchecked, and provide any additional information or questions in the "Additional information" section below.
      options:
        - label: I have checked that the site meets the Passkey Directory's [site eligibility criteria](https://github.com/2factorauth/passkeys/blob/master/CONTRIBUTING.md)
        - label: The site is ranked within the top 200,000 global sites on [Similarweb](https://www.similarweb.com/).
        - label: The issue I'm creating is not a duplicate of an existing [issue](https://github.com/2factorauth/passkeys/issues) or [pull request](https://github.com/2factorauth/passkeys/pulls).
          required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional information
      description: If you have any additional information, please provide it here.
